Update actions.yml

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -1,33 +1,30 @@
 name: Validate Build and Tests
-
 on:
   push:
     branches: [main]
-
 jobs:
-  build:
+  #Test's job
+  tests:
+    name: Unit tests
+    #Run on Ubuntu using the latest version
     runs-on: ubuntu-latest
-
+    #Job's steps
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-
-    - name: Set up JDK 11
-      uses: actions/setup-java@v2
-      with:
-        java-version: '11'
-
-    - name: Build with Maven
-      run: mvn -B package --file pom.xml
-
-    - name: Run tests with Maven
-      run: mvn test --file pom.xml
-
-    - name: Validate build and tests
-      run: |
-        if [ ${{ steps.build.outcome }} == 'success' ] && [ ${{ steps.tests.outcome }} == 'success' ]; then
-          echo "Build and tests passed!"
-        else
-          echo "Build or tests failed!"
-          exit 1
-        fi
+      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
+      - uses: actions/checkout@v1
+      #Set up JDK 11
+      - name: Set up JDK
+        uses: actions/setup-java@v1
+        with:
+          java-version: '11'
+      - name: Build with Maven
+        run: mvn -B package --file pom.xml
+      - name: Run tests with Maven
+        run: mvn test --file pom.xml
+      - name: Validate build and tests
+        run: |
+          if [ ${{ steps.build.outcome }} == 'success' ] && [ ${{ steps.tests.outcome }} == 'success' ]; then
+            echo "Build and tests passed!"
+          else
+            echo "Build or tests failed!"
+            exit 1
