Update actions.yml

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -2,17 +2,15 @@ name: Validate Build and Tests
 
 on:
   push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+    branches: [main]
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
+    - name: Checkout code
+      uses: actions/checkout@v2
 
     - name: Set up JDK 11
       uses: actions/setup-java@v2
@@ -22,5 +20,14 @@ jobs:
     - name: Build with Maven
       run: mvn -B package --file pom.xml
 
-    - name: Test with Maven
-      run: mvn -B test --file pom.xml
+    - name: Run tests with Maven
+      run: mvn test --file pom.xml
+
+    - name: Validate build and tests
+      run: |
+        if [ ${{ steps.build.outcome }} == 'success' ] && [ ${{ steps.tests.outcome }} == 'success' ]; then
+          echo "Build and tests passed!"
+        else
+          echo "Build or tests failed!"
+          exit 1
+        fi
